language: python
python:
  - "3.9"
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src

install:
  - pip install pipenv
  - make install

stages:
  - style
  - test

jobs:
  include:
    - stage: style
      name: "Style check"
      script: make lint
    - stage: test
      name: "Unit tests"
      script: pytest -v --color=yes src # Runs in pipenv
