name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        ru: |
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Run test suite
        run: |
          pytest